### ISSUE TITLE
feat: handle custom cache paths

### ISSUE THREAD

**Issue by antongolub** [antongolub/action-setup-bun#6]
https://github.com/oven-sh/bun#bun-install
```toml
[install.cache]
# The directory to use for the cache
dir = "~/.bun/install/cache"
```
